In [2]:
import numpy as np

## Solução dos Mínimos Quadrados

$$
\begin{align}
\hat{x} = arg \min_x \|A x - b \|^2 & \Rightarrow A^TA\hat{x} = A^Tb\\
&\Rightarrow \hat{x} = (A^T A)^{-1}A^Tb\\
&\Rightarrow \hat{x} = A^+b\\
\end{align}
$$

Onde $A^+$ é a pseudo inversa de Moore-Penrose

__OBS__: Se $Ax=b$ possui solução exata, então $\hat{x}$ é a solução

### Verificação direta que $\hat{x}$ é solução

Para todo $x \neq \hat{x}$, vamos mostrar que $\|A\hat{x} -b\|^2 <\  \|Ax -b\|^2$

__Lembrete__: $ \| u + v\|^2 = (u+v)^T(u+v) = \|u\|^2 + \|v\|^2 + 2 u^Tv$.

Temos:
$$
\begin{align*}
\|Ax-b\|^2 &= \|Ax\  {\color{cyan}- A\hat{x} + A\hat{x}} - b\|^2 \\
&=\|Ax - A\hat{x}\|^2 + \| A\hat{x} - b\|^2 + 2\  \color{yellow}{(Ax - A\hat{x})^T( A\hat{x} - b)}.
\end{align*}
$$

Observe que:

$$
\begin{align*}
\color{yellow}{(Ax - A\hat{x})^T( A\hat{x} - b)} &= (x^TA^T - \hat{x}^TA^T)( A\hat{x} - b)\\
&=(x^T - \hat{x}^T)A^T( A\hat{x} - b)\\
&=(x - \hat{x})^TA^T( A\hat{x} - b)\\
&=(x - \hat{x})^T( A^TA\hat{x} - A^Tb)\\
&=(x - \hat{x})^T( A^TA\hat{x} - A^Tb)\\
&=(x - \hat{x})^T\mathbf{0}\\
&=0\\
\end{align*}
$$

Dessa forma:

$$
\begin{align*}
\|Ax-b\|^2 =\|A(x - \hat{x})\|^2 + \| A\hat{x} - b\|^2.
\end{align*}
$$

como $\|A(x - \hat{x})\|^2 > 0$, pois $A$ tem colunas linearmente independentes, logo:
$$
Ay = [\vec{a}_1, \vec{a}_2, .., \vec{a}_n ] \vec{y} = \vec{a}_1y_1 + \vec{a}_2 y_2 + ... + \vec{a}_n y_n = 0 \iff y_1 = y_2 = ... = y_n = 0
$$

e $y = x - \hat{x} = 0 \iff x = \hat{x}$ mas $x \neq \hat{x}$, portanto: 

$$
\begin{align*}
\|Ax-b\|^2 >  \| A\hat{x} - b\|^2.
\end{align*}
$$


### Implementando o Método dos Minimos Quadrados (MMQ)

$$
\begin{align}
&\hat{x} = (A^T A)^{-1}A^Tb\\
\Rightarrow &\hat{x} = A^+b\\
\end{align}
$$

## Método SVD

Decomposição SVD: $A = U \Sigma V^T \Rightarrow A^T = V \Sigma U^T$

__Lembrete__: $(AB)^{-1} = B^{-1}A^{-1}$, pois $(AB)(B^{-1}A^{-1}) = A I A^{-1} = I$
$$
\begin{align*}
A^+ &= (A^TA)^{-1}A^T\\
 &= (V \Sigma U^T U \Sigma V^T)^{-1}V \Sigma U^T\\
 &= (V \Sigma \Sigma V^T)^{-1}V \Sigma U^T\\
 &= (V \Sigma^2 V^T)^{-1}V \Sigma U^T\\
 &= (V \Sigma^2 V^T)^{-1}V \Sigma U^T\\
 &= V^{-T} \Sigma^{-2} V^{-1}V \Sigma U^T\\
 &= V^{-T} \Sigma^{-2} \Sigma U^T\\
 &= V^{-T} \Sigma^{-1} U^T\\
 &= (V^{T})^{-1} \Sigma^{-1} U^T\\
 &= V \Sigma^{-1} U^T\\
\end{align*}
$$



## Método QR
Decomposição QR: $A = QR \Rightarrow A^T = R^TQ^T$

$$
\begin{align*}
A^+ &= (A^TA)^{-1}A^T\\
 &= (R^TQ^TQR)^{-1}R^TQ^T\\
 &= (R^TR)^{-1}R^TQ^T\\
 &= R^{-1}R^{-T}R^TQ^T\\
 &= R^{-1}Q^T\\
\end{align*}
$$

Logo:
$$
\begin{align*}
 \hat{x} &= A^+b = R^{-1}Q^Tb\\
&\Rightarrow R\hat{x} =R R^{-1}Q^Tb\\
&\Rightarrow R\hat{x} =Q^Tb, \\
\end{align*}
$$
Seja $y = Q^Tb$, basta resolver o sistema triangular $R\hat{x} =y$

In [12]:
# Implementação da solução
A = np.random.rand(10, 3)
b = np.random.rand(10, 1)

x = np.linalg.lstsq(A,b,rcond=0)[0]
print(x)
print()
def mmq_1(A, b):
    M = A.T@A
    y= A.T@b
    x = np.linalg.solve(M,y)
    return x

x_1 = mmq_1(A,b)
print(x_1)
print()
# SVD
def mmq_svd(A,b):
    U, S, Vt = np.linalg.svd(A, full_matrices=False)
    iS = 1. / S

    piA = Vt.T @ np.diag(iS) @ U.T
    x = piA @ b
    return x

x_svd = mmq_svd(A,b)
print(x_svd)
print()
# QR

def mmq_qr(A,b):
    Q,R = np.linalg.qr(A)
    y = Q.T @ b
    x = np.linalg.solve(R,y)
    return x
x_qr = mmq_qr(A,b)

print(x_qr)
print()


[[ 0.80010123]
 [ 0.36473871]
 [-0.25567562]]

[[ 0.80010123]
 [ 0.36473871]
 [-0.25567562]]

[[ 0.80010123]
 [ 0.36473871]
 [-0.25567562]]

[[ 0.80010123]
 [ 0.36473871]
 [-0.25567562]]



#### Um pouco sobre como calcular o SVD

$$
A_1 = A\\
QR(A_1) = Q_1R_1\\
A_2 = R_1Q_1\\
QR(A_2) = Q_2R_2\\
A_3 = R_2Q_2\\
\vdots\\
A_{k+1} = R_{k}Q_{k}
$$